# Do not choose a language; we provide our own build tools.
language: generic

cache:
  directories:
  - $HOME/.stack

# Notification receivers
notifications:
  email: false

matrix:
  fast_finish: true
  include:
  # Build with the stack
  - env: BUILD=stack ARGS="--resolver lts-3"
    compiler: "#stack LTS-3 (7.10.2)"
    addons:
      apt:
        packages: [libgmp-dev]

  - env: BUILD=stack ARGS=""
    compiler: "#stack default"
    addons:
      apt:
        packages: [libgmp-dev]

  # Nightly builds are allowed to fail
  - env: BUILD=stack ARGS="--resolver nightly"
    compiler: "#stack nightly"
    addons:
      apt:
        packages: [libgmp-dev]

  # Build on OS X in addition to Linux
  - env: BUILD=stack ARGS=""
    compiler: "#stack default osx"
    os: osx

  # Nightly builds are allowed to fail
  - env: BUILD=stack ARGS="--resolver nightly"
    compiler: "#stack nightly osx"
    os: osx

  - env: BUILD=style ARGS=""
    compiler: "#stack default style"

  allow_failures:
  - env: BUILD=stack ARGS="--resolver nightly"

before_install: source travis/before_install.sh

install: source travis/install.sh

script: source travis/script.sh
