#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

# caching
cache:
  - stack.exe
  - '%APPDATA%\stack -> *.yml'
  - '%APPDATA%\local\bin'

# scripts that run after cloning repository
install: appveyor/install.cmd

environment:
  matrix:
    - build: stack
      args: --resolver lts-3
    - build: stack
      args:
    - build: stack
      args: --resolver nightly
    - build: style
      args:

matrix:
  fast_finish: true
  allow_failures:
    - build: stack
      args: --resolver nightly

#---------------------------------#
#       build configuration       #
#---------------------------------#

# scripts to run before build
before_build: appveyor/before_build.cmd

# to run your custom scripts instead of automatic MSBuild
build_script: appveyor/build_script.cmd
